import type { FieldDefinition } from '../types'

export const field: FieldDefinition = {
  key: 'imb_reg_of_religion',
  labelKey: 'peopleGroups.fields.imb_reg_of_religion',
  type: 'select',
  category: 'religion',
  tableColumn: true,
  options: [
    { value: 'BOF', labelKey: 'peopleGroups.options.religion.BOF' },
    { value: 'BMA', labelKey: 'peopleGroups.options.religion.BMA' },
    { value: 'BTH', labelKey: 'peopleGroups.options.religion.BTH' },
    { value: 'BLA', labelKey: 'peopleGroups.options.religion.BLA' },
    { value: 'COR', labelKey: 'peopleGroups.options.religion.COR' },
    { value: 'CFC', labelKey: 'peopleGroups.options.religion.CFC' },
    { value: 'CNP', labelKey: 'peopleGroups.options.religion.CNP' },
    { value: 'CPR', labelKey: 'peopleGroups.options.religion.CPR' },
    { value: 'CRC', labelKey: 'peopleGroups.options.religion.CRC' },
    { value: 'E', labelKey: 'peopleGroups.options.religion.E' },
    { value: 'EAF', labelKey: 'peopleGroups.options.religion.EAF' },
    { value: 'EAW', labelKey: 'peopleGroups.options.religion.EAW' },
    { value: 'EAN', labelKey: 'peopleGroups.options.religion.EAN' },
    { value: 'ECF', labelKey: 'peopleGroups.options.religion.ECF' },
    { value: 'ECO', labelKey: 'peopleGroups.options.religion.ECO' },
    { value: 'EDA', labelKey: 'peopleGroups.options.religion.EDA' },
    { value: 'ENA', labelKey: 'peopleGroups.options.religion.ENA' },
    { value: 'EPO', labelKey: 'peopleGroups.options.religion.EPO' },
    { value: 'ESA', labelKey: 'peopleGroups.options.religion.ESA' },
    { value: 'ESM', labelKey: 'peopleGroups.options.religion.ESM' },
    { value: 'EJF', labelKey: 'peopleGroups.options.religion.EJF' },
    { value: 'H', labelKey: 'peopleGroups.options.religion.H' },
    { value: 'HOF', labelKey: 'peopleGroups.options.religion.HOF' },
    { value: 'MOF', labelKey: 'peopleGroups.options.religion.MOF' },
    { value: 'MSH', labelKey: 'peopleGroups.options.religion.MSH' },
    { value: 'MIS', labelKey: 'peopleGroups.options.religion.MIS' },
    { value: 'MSN', labelKey: 'peopleGroups.options.religion.MSN' },
    { value: 'J', labelKey: 'peopleGroups.options.religion.J' },
    { value: 'OBH', labelKey: 'peopleGroups.options.religion.OBH' },
    { value: 'ODZ', labelKey: 'peopleGroups.options.religion.ODZ' },
    { value: 'OJA', labelKey: 'peopleGroups.options.religion.OJA' },
    { value: 'OKI', labelKey: 'peopleGroups.options.religion.OKI' },
    { value: 'OMA', labelKey: 'peopleGroups.options.religion.OMA' },
    { value: 'OZR', labelKey: 'peopleGroups.options.religion.OZR' },
    { value: 'S', labelKey: 'peopleGroups.options.religion.S' },
    { value: 'N', labelKey: 'peopleGroups.options.religion.N' },
    { value: 'NAG', labelKey: 'peopleGroups.options.religion.NAG' },
    { value: 'NAT', labelKey: 'peopleGroups.options.religion.NAT' },
    { value: 'NSE', labelKey: 'peopleGroups.options.religion.NSE' },
    { value: 'U', labelKey: 'peopleGroups.options.religion.U' }
  ]
}
