import type { FieldDefinition, FieldOption } from '../types'

export const options: FieldOption[] = [
  { value: 'abkhaz-adyge', label: 'Abkhaz-Adyge' },
  { value: 'afro-asiatic', label: 'Afro-Asiatic' },
  { value: 'algic', label: 'Algic' },
  { value: 'amto-musan', label: 'Amto-Musan' },
  { value: 'angan', label: 'Angan' },
  { value: 'anim', label: 'Anim' },
  { value: 'arafundi', label: 'Arafundi' },
  { value: 'araucanian', label: 'Araucanian' },
  { value: 'arawakan', label: 'Arawakan' },
  { value: 'arawan', label: 'Arawan' },
  { value: 'athabaskan-eyak-tlingit', label: 'Athabaskan-Eyak-Tlingit' },
  { value: 'atlantic-congo', label: 'Atlantic-Congo' },
  { value: 'austroasiatic', label: 'Austroasiatic' },
  { value: 'austronesian', label: 'Austronesian' },
  { value: 'aymaran', label: 'Aymaran' },
  { value: 'baibai-fas', label: 'Baibai-Fas' },
  { value: 'baining', label: 'Baining' },
  { value: 'barbacoan', label: 'Barbacoan' },
  { value: 'bayono-awbono', label: 'Bayono-Awbono' },
  { value: 'blue_nile_mao', label: 'Blue Nile Mao' },
  { value: 'bogia', label: 'Bogia' },
  { value: 'bookkeeping', label: 'Bookkeeping' },
  { value: 'boran', label: 'Boran' },
  { value: 'border', label: 'Border' },
  { value: 'bororoan', label: 'Bororoan' },
  { value: 'bosavi', label: 'Bosavi' },
  { value: 'bulaka_river', label: 'Bulaka River' },
  { value: 'cahuapanan', label: 'Cahuapanan' },
  { value: 'cariban', label: 'Cariban' },
  { value: 'central_sudanic', label: 'Central Sudanic' },
  { value: 'chapacuran', label: 'Chapacuran' },
  { value: 'chibchan', label: 'Chibchan' },
  { value: 'chicham', label: 'Chicham' },
  { value: 'chocoan', label: 'Chocoan' },
  { value: 'cochimi-yuman', label: 'Cochimi-Yuman' },
  { value: 'dagan', label: 'Dagan' },
  { value: 'dajuic', label: 'Dajuic' },
  { value: 'dizoid', label: 'Dizoid' },
  { value: 'dogon', label: 'Dogon' },
  { value: 'dravidian', label: 'Dravidian' },
  { value: 'east_bird\'s_head', label: 'East Bird\'s Head' },
  { value: 'east_kutubu', label: 'East Kutubu' },
  { value: 'east_strickland', label: 'East Strickland' },
  { value: 'eastern_jebel', label: 'Eastern Jebel' },
  { value: 'eastern_trans-fly', label: 'Eastern Trans-Fly' },
  { value: 'eleman', label: 'Eleman' },
  { value: 'eskimo-aleut', label: 'Eskimo-Aleut' },
  { value: 'furan', label: 'Furan' },
  { value: 'garrwan', label: 'Garrwan' },
  { value: 'geelvink_bay', label: 'Geelvink Bay' },
  { value: 'greater_kwerba', label: 'Greater Kwerba' },
  { value: 'guahiboan', label: 'Guahiboan' },
  { value: 'guaicuruan', label: 'Guaicuruan' },
  { value: 'gumuz', label: 'Gumuz' },
  { value: 'gunwinyguan', label: 'Gunwinyguan' },
  { value: 'harakmbut', label: 'Harakmbut' },
  { value: 'hatam-mansim', label: 'Hatam-Mansim' },
  { value: 'heibanic', label: 'Heibanic' },
  { value: 'hmong-mien', label: 'Hmong-Mien' },
  { value: 'huavean', label: 'Huavean' },
  { value: 'huitotoan', label: 'Huitotoan' },
  { value: 'ijoid', label: 'Ijoid' },
  { value: 'indo-european', label: 'Indo-European' },
  { value: 'iroquoian', label: 'Iroquoian' },
  { value: 'iwaidjan_proper', label: 'Iwaidjan Proper' },
  { value: 'japonic', label: 'Japonic' },
  { value: 'jarawa-onge', label: 'Jarawa-Onge' },
  { value: 'jarrakan', label: 'Jarrakan' },
  { value: 'jicaquean', label: 'Jicaquean' },
  { value: 'kadugli-krongo', label: 'Kadugli-Krongo' },
  { value: 'kakua-nukak', label: 'Kakua-Nukak' },
  { value: 'kamula-elevala', label: 'Kamula-Elevala' },
  { value: 'kartvelian', label: 'Kartvelian' },
  { value: 'katla-tima', label: 'Katla-Tima' },
  { value: 'katukinan', label: 'Katukinan' },
  { value: 'kaure-kosare', label: 'Kaure-Kosare' },
  { value: 'kayagaric', label: 'Kayagaric' },
  { value: 'keram', label: 'Keram' },
  { value: 'keresan', label: 'Keresan' },
  { value: 'khoe-kwadi', label: 'Khoe-Kwadi' },
  { value: 'kiowa-tanoan', label: 'Kiowa-Tanoan' },
  { value: 'kiwaian', label: 'Kiwaian' },
  { value: 'koiarian', label: 'Koiarian' },
  { value: 'kolopom', label: 'Kolopom' },
  { value: 'koman', label: 'Koman' },
  { value: 'konda-yahadian', label: 'Konda-Yahadian' },
  { value: 'koreanic', label: 'Koreanic' },
  { value: 'kresh-aja', label: 'Kresh-Aja' },
  { value: 'kru', label: 'Kru' },
  { value: 'kuliak', label: 'Kuliak' },
  { value: 'kunimaipan', label: 'Kunimaipan' },
  { value: 'kwalean', label: 'Kwalean' },
  { value: 'kwomtari-nai', label: 'Kwomtari-Nai' },
  { value: 'kxa', label: 'Kxa' },
  { value: 'lakes_plain', label: 'Lakes Plain' },
  { value: 'left_may', label: 'Left May' },
  { value: 'lengua-mascoy', label: 'Lengua-Mascoy' },
  { value: 'lepki-murkim-kembra', label: 'Lepki-Murkim-Kembra' },
  { value: 'lower_sepik', label: 'Lower Sepik' },
  { value: 'maban', label: 'Maban' },
  { value: 'mailuan', label: 'Mailuan' },
  { value: 'mairasic', label: 'Mairasic' },
  { value: 'mande', label: 'Mande' },
  { value: 'maningrida', label: 'Maningrida' },
  { value: 'manubaran', label: 'Manubaran' },
  { value: 'mataguayan', label: 'Mataguayan' },
  { value: 'mayan', label: 'Mayan' },
  { value: 'maybratic', label: 'Maybratic' },
  { value: 'misumalpan', label: 'Misumalpan' },
  { value: 'mixe-zoque', label: 'Mixe-Zoque' },
  { value: 'mixed_language', label: 'Mixed language' },
  { value: 'mombum-koneraw', label: 'Mombum-Koneraw' },
  { value: 'mongolic-khitan', label: 'Mongolic-Khitan' },
  { value: 'muskogean', label: 'Muskogean' },
  { value: 'naduhup', label: 'Naduhup' },
  { value: 'nakh-daghestanian', label: 'Nakh-Daghestanian' },
  { value: 'nambiquaran', label: 'Nambiquaran' },
  { value: 'namla-tofanma', label: 'Namla-Tofanma' },
  { value: 'narrow_talodi', label: 'Narrow Talodi' },
  { value: 'ndu', label: 'Ndu' },
  { value: 'niger-congo', label: 'Niger-Congo' },
  { value: 'nilotic', label: 'Nilotic' },
  { value: 'nimboranic', label: 'Nimboranic' },
  { value: 'none', label: 'None' },
  { value: 'north_halmahera', label: 'North Halmahera' },
  { value: 'nubian', label: 'Nubian' },
  { value: 'nuclear_torricelli', label: 'Nuclear Torricelli' },
  { value: 'nuclear_trans_new_guinea', label: 'Nuclear Trans New Guinea' },
  { value: 'nuclear-macro-je', label: 'Nuclear-Macro-Je' },
  { value: 'nyimang', label: 'Nyimang' },
  { value: 'nyulnyulan', label: 'Nyulnyulan' },
  { value: 'otomanguean', label: 'Otomanguean' },
  { value: 'pahoturi', label: 'Pahoturi' },
  { value: 'pama-nyungan', label: 'Pama-Nyungan' },
  { value: 'pano-tacanan', label: 'Pano-Tacanan' },
  { value: 'pauwasi', label: 'Pauwasi' },
  { value: 'peba-yagua', label: 'Peba-Yagua' },
  { value: 'piawi', label: 'Piawi' },
  { value: 'pidgin', label: 'Pidgin' },
  { value: 'quechuan', label: 'Quechuan' },
  { value: 'ramu', label: 'Ramu' },
  { value: 'rashad', label: 'Rashad' },
  { value: 'saharan', label: 'Saharan' },
  { value: 'saliban', label: 'Saliban' },
  { value: 'senagi', label: 'Senagi' },
  { value: 'sentanic', label: 'Sentanic' },
  { value: 'sepik', label: 'Sepik' },
  { value: 'sign_language', label: 'Sign language' },
  { value: 'sino-tibetan', label: 'Sino-Tibetan' },
  { value: 'siouan', label: 'Siouan' },
  { value: 'sko', label: 'Sko' },
  { value: 'somahai', label: 'Somahai' },
  { value: 'songhay', label: 'Songhay' },
  { value: 'south_bird\'s_head', label: 'South Bird\'s Head' },
  { value: 'south_omotic', label: 'South Omotic' },
  { value: 'south-eastern_tasmanian', label: 'South-Eastern Tasmanian' },
  { value: 'southern_daly', label: 'Southern Daly' },
  { value: 'speech_register', label: 'Speech Register' },
  { value: 'suki-gogodala', label: 'Suki-Gogodala' },
  { value: 'surmic', label: 'Surmic' },
  { value: 'ta-ne-omotic', label: 'Ta-Ne-Omotic' },
  { value: 'tai-kadai', label: 'Tai-Kadai' },
  { value: 'tamaic', label: 'Tamaic' },
  { value: 'tarascan', label: 'Tarascan' },
  { value: 'taulil-butam', label: 'Taulil-Butam' },
  { value: 'teberan', label: 'Teberan' },
  { value: 'tegem', label: 'Tegem' },
  { value: 'temeinic', label: 'Temeinic' },
  { value: 'ticuna-yuri', label: 'Ticuna-Yuri' },
  { value: 'timor-alor-pantar', label: 'Timor-Alor-Pantar' },
  { value: 'tor-orya', label: 'Tor-Orya' },
  { value: 'totonacan', label: 'Totonacan' },
  { value: 'tsimshian', label: 'Tsimshian' },
  { value: 'tucanoan', label: 'Tucanoan' },
  { value: 'tungusic', label: 'Tungusic' },
  { value: 'tupian', label: 'Tupian' },
  { value: 'turama-kikori', label: 'Turama-Kikori' },
  { value: 'turkic', label: 'Turkic' },
  { value: 'tuu', label: 'Tuu' },
  { value: 'unattested', label: 'Unattested' },
  { value: 'unclassifiable', label: 'Unclassifiable' },
  { value: 'uralic', label: 'Uralic' },
  { value: 'uru-chipaya', label: 'Uru-Chipaya' },
  { value: 'uto-aztecan', label: 'Uto-Aztecan' },
  { value: 'wakashan', label: 'Wakashan' },
  { value: 'walioic', label: 'Walioic' },
  { value: 'west_bird\'s_head', label: 'West Bird\'s Head' },
  { value: 'west_bomberai', label: 'West Bomberai' },
  { value: 'worrorran', label: 'Worrorran' },
  { value: 'yam', label: 'Yam' },
  { value: 'yanomamic', label: 'Yanomamic' },
  { value: 'yareban', label: 'Yareban' },
  { value: 'yawa-saweru', label: 'Yawa-Saweru' },
  { value: 'yuat', label: 'Yuat' },
  { value: 'zamucoan', label: 'Zamucoan' },
  { value: 'zaparoan', label: 'Zaparoan' }
]

export const field: FieldDefinition = {
  key: 'imb_language_family',
  labelKey: 'peopleGroups.fields.imb_language_family',
  type: 'select',
  category: 'language',
  options
}
