import type { FieldDefinition } from '../types'

export const field: FieldDefinition = {
  key: 'imb_reg_of_religion_4',
  labelKey: 'peopleGroups.fields.imb_reg_of_religion_4',
  type: 'select',
  category: 'religion',
  options: [
    { value: 'EAF', labelKey: 'peopleGroups.options.ror4.EAF' },
    { value: 'NAG', labelKey: 'peopleGroups.options.ror4.NAG' },
    { value: 'EAW', labelKey: 'peopleGroups.options.ror4.EAW' },
    { value: 'EAN', labelKey: 'peopleGroups.options.ror4.EAN' },
    { value: 'NAT', labelKey: 'peopleGroups.options.ror4.NAT' },
    { value: 'OBH', labelKey: 'peopleGroups.options.ror4.OBH' },
    { value: 'ECF', labelKey: 'peopleGroups.options.ror4.ECF' },
    { value: 'ECO', labelKey: 'peopleGroups.options.ror4.ECO' },
    { value: 'EDA', labelKey: 'peopleGroups.options.ror4.EDA' },
    { value: 'ODZ', labelKey: 'peopleGroups.options.ror4.ODZ' },
    { value: 'COR', labelKey: 'peopleGroups.options.ror4.COR' },
    { value: 'BOF', labelKey: 'peopleGroups.options.ror4.BOF' },
    { value: 'CFC', labelKey: 'peopleGroups.options.ror4.CFC' },
    { value: 'HOF', labelKey: 'peopleGroups.options.ror4.HOF' },
    { value: 'MOF', labelKey: 'peopleGroups.options.ror4.MOF' },
    { value: 'OJA', labelKey: 'peopleGroups.options.ror4.OJA' },
    { value: 'OKI', labelKey: 'peopleGroups.options.ror4.OKI' },
    { value: 'BMA', labelKey: 'peopleGroups.options.ror4.BMA' },
    { value: 'OMA', labelKey: 'peopleGroups.options.ror4.OMA' },
    { value: 'ENA', labelKey: 'peopleGroups.options.ror4.ENA' },
    { value: 'CNP', labelKey: 'peopleGroups.options.ror4.CNP' },
    { value: 'EPO', labelKey: 'peopleGroups.options.ror4.EPO' },
    { value: 'CPR', labelKey: 'peopleGroups.options.ror4.CPR' },
    { value: 'CRC', labelKey: 'peopleGroups.options.ror4.CRC' },
    { value: 'ESA', labelKey: 'peopleGroups.options.ror4.ESA' },
    { value: 'NSE', labelKey: 'peopleGroups.options.ror4.NSE' },
    { value: 'ESM', labelKey: 'peopleGroups.options.ror4.ESM' },
    { value: 'MIS', labelKey: 'peopleGroups.options.ror4.MIS' },
    { value: 'MSH', labelKey: 'peopleGroups.options.ror4.MSH' },
    { value: 'EJF', labelKey: 'peopleGroups.options.ror4.EJF' },
    { value: 'MSN', labelKey: 'peopleGroups.options.ror4.MSN' },
    { value: 'BTH', labelKey: 'peopleGroups.options.ror4.BTH' },
    { value: 'BLA', labelKey: 'peopleGroups.options.ror4.BLA' },
    { value: 'OZR', labelKey: 'peopleGroups.options.ror4.OZR' }
  ]
}
